<template>
  <!-- 左侧列表栏数据列表 -->
  <ul>
    <li
        v-for="(item,index) in list"
        :key="index"
        class="getItem"
        :data-shape="item.shape"
        :data-type="item.type"
        :data-size="item.size"
        draggable="true"
        @dragstart="handleDragstart"
        @dragend="handleDragEnd($event,item)"
    >
      <span class="pannel-type-icon" :style="{background:'url('+item.image+')'}"></span>
      <span class="item-name">{{ item.name }}</span>
    </li>
  </ul>
</template>

<script>
import eventBus from "../../utils/eventBus";
import okSvg from "../../assets/icons/ok.svg";
import bgImg from "../../assets/bg.jpg";

export default {
  data() {
    return {
      page: null,
      command: null,
      offsetX: 0,
      offsetY: 0,
      list: [
        {
          name: "测试节点",
          label: "测试节点",
          size: "170*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]]
        },
        {
          name: "背景图片节点",
          label: "背景图片节点",
          size: "170*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          backImage: bgImg,
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]]
        },
        {
          name: "双输出节点",
          label: "双输出节点",
          size: "170*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.4], [1, 0.6]]
        },
        {
          name: "大型节点",
          label: "大型节点",
          size: "340*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]]
        },
        {
          name: "动画开始节点",
          label: "动画开始",
          size: "170*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          outPoints: [[1, 0.5]],
          isDoingStart: true
        },
        {
          name: "动画结束节点",
          label: "动画结束",
          size: "170*34",
          type: "node",
          x: 0,
          y: 0,
          shape: "customNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          stateImage: okSvg,
          inPoints: [[0, 0.5]],
          isDoingEnd: true
        },
        {
          label: "文本卡",
          size: "290*90",
          type: "node",
          x: 0,
          y: 0,
          shape: "textCardNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]],
          isDoingStart: true,
          id: 58,
          name: "国内酒店抵扣有效订单比（创单）",
          enName: "hotel_mile_sorders_rate",
          groupType: 3,
          period: '1h',
          card: {value: "109.00", dodRate: "-209.68%", wowRate: "430.42%", hohRate: "230.03%", time: "14:30 - 14:35"},
          viewComparison: ["dod", "wow"],
          table: {},
          trend: {},
        },
        {
          label: "表格",
          size: "485*280",
          type: "node",
          x: 0,
          y: 0,
          shape: "tableNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]],
          isDoingStart: true,
          id: 53,
          name: "国内酒店抵扣有效订单比（离店）",
          enName: "hotel_mile_sorders",
          groupType: 3,
          period: '1d',
          card: {value: "109.00", dodRate: "-209.68%", wowRate: "430.42%", hohRate: "230.03%", time: "14:30 - 14:35"},
          viewComparison: ["dod", "wow"],
          table: {},
          trend: {},
          tableData: [{
            timePeriod: "00:05",
            value: "5.53%",
            hohRate: "--",
            dodRate: "-1.0%",
            wowRate: "-0.75%"
          }, {
            timePeriod: "00:10",
            value: "6.77%",
            hohRate: "--",
            dodRate: "2.13%",
            wowRate: "1.21%"
          }, {
            timePeriod: "00:15",
            value: "5.47%",
            hohRate: "--",
            dodRate: "-1.74%",
            wowRate: "-0.52%"
          }, {
            timePeriod: "00:20",
            value: "5.58%",
            hohRate: "--",
            dodRate: "-1.16%",
            wowRate: "-1.08%"
          }, {
            timePeriod: "00:25",
            value: "4.91%",
            hohRate: "--",
            dodRate: "-1.88%",
            wowRate: "-1.16%"
          }, {
            timePeriod: "00:30",
            value: "5.51%",
            hohRate: "--",
            dodRate: "0.02%",
            wowRate: "0.15%"
          }, {
            timePeriod: "00:35",
            value: "5.87%",
            hohRate: "--",
            dodRate: "-0.28%",
            wowRate: "-1.48%"
          }, {
            timePeriod: "00:40",
            value: "5.55%",
            hohRate: "--",
            dodRate: "0.05%",
            wowRate: "-1.61%"
          }, {
            timePeriod: "00:45",
            value: "6.22%",
            hohRate: "--",
            dodRate: "0.31%",
            wowRate: "-0.86%"
          }, {
            timePeriod: "00:50",
            value: "6.60%",
            hohRate: "--",
            dodRate: "0.7%",
            wowRate: "0.08%"
          }, {
            timePeriod: "00:55",
            value: "5.49%",
            hohRate: "--",
            dodRate: "-0.82%",
            wowRate: "-0.77%"
          }, {
            timePeriod: "01:00",
            value: "6.71%",
            hohRate: "--",
            dodRate: "0.86%",
            wowRate: "-0.4%"
          }, {
            timePeriod: "01:05",
            value: "5.31%",
            hohRate: "--",
            dodRate: "-0.75%",
            wowRate: "-0.46%"
          }, {
            timePeriod: "01:10",
            value: "6.19%",
            hohRate: "--",
            dodRate: "0.89%",
            wowRate: "-1.01%"
          }, {
            timePeriod: "01:15",
            value: "5.61%",
            hohRate: "--",
            dodRate: "-1.15%",
            wowRate: "-0.64%"
          }, {
            timePeriod: "01:20",
            value: "6.38%",
            hohRate: "--",
            dodRate: "0.75%",
            wowRate: "-1.13%"
          }, {
            timePeriod: "01:25",
            value: "6.03%",
            hohRate: "--",
            dodRate: "-0.94%",
            wowRate: "0.31%"
          }, {
            timePeriod: "01:30",
            value: "5.81%",
            hohRate: "--",
            dodRate: "-0.79%",
            wowRate: "0.26%"
          }, {
            timePeriod: "01:35",
            value: "6.67%",
            hohRate: "--",
            dodRate: "0.91%",
            wowRate: "0.13%"
          }, {
            timePeriod: "01:40",
            value: "5.04%",
            hohRate: "--",
            dodRate: "-1.5%",
            wowRate: "-0.78%"
          }, {
            timePeriod: "01:45",
            value: "7.07%",
            hohRate: "--",
            dodRate: "1.15%",
            wowRate: "-1.77%"
          }, {
            timePeriod: "01:50",
            value: "6.60%",
            hohRate: "--",
            dodRate: "1.56%",
            wowRate: "-0.77%"
          }, {
            timePeriod: "01:55",
            value: "6.00%",
            hohRate: "--",
            dodRate: "0.8%",
            wowRate: "0.06%"
          }, {
            timePeriod: "02:00",
            value: "6.70%",
            hohRate: "--",
            dodRate: "0.26%",
            wowRate: "1.22%"
          }, {
            timePeriod: "02:05",
            value: "6.02%",
            hohRate: "--",
            dodRate: "-0.64%",
            wowRate: "0.14%"
          }, {
            timePeriod: "02:10",
            value: "6.27%",
            hohRate: "--",
            dodRate: "0.42%",
            wowRate: "-1.03%"
          }, {
            timePeriod: "02:15",
            value: "7.09%",
            hohRate: "--",
            dodRate: "-0.86%",
            wowRate: "0.7%"
          }, {
            timePeriod: "02:20",
            value: "5.79%",
            hohRate: "--",
            dodRate: "-0.54%",
            wowRate: "1.03%"
          }, {
            timePeriod: "02:25",
            value: "9.15%",
            hohRate: "--",
            dodRate: "3.06%",
            wowRate: "1.3%"
          }, {
            timePeriod: "02:30",
            value: "8.00%",
            hohRate: "--",
            dodRate: "2.34%",
            wowRate: "1.46%"
          }, {
            timePeriod: "02:35",
            value: "8.13%",
            hohRate: "--",
            dodRate: "0.8%",
            wowRate: "0.43%"
          }, {
            timePeriod: "02:40",
            value: "5.25%",
            hohRate: "--",
            dodRate: "-0.83%",
            wowRate: "-1.19%"
          }, {
            timePeriod: "02:45",
            value: "5.83%",
            hohRate: "--",
            dodRate: "-1.88%",
            wowRate: "-1.16%"
          }, {
            timePeriod: "02:50",
            value: "5.68%",
            hohRate: "--",
            dodRate: "-0.85%",
            wowRate: "-1.33%"
          }, {
            timePeriod: "02:55",
            value: "5.93%",
            hohRate: "--",
            dodRate: "-1.13%",
            wowRate: "-0.56%"
          }, {
            timePeriod: "03:00",
            value: "6.64%",
            hohRate: "--",
            dodRate: "-0.47%",
            wowRate: "0.33%"
          }, {
            timePeriod: "03:05",
            value: "6.23%",
            hohRate: "--",
            dodRate: "-1.48%",
            wowRate: "-1.87%"
          }, {
            timePeriod: "03:10",
            value: "6.14%",
            hohRate: "--",
            dodRate: "-0.14%",
            wowRate: "1.51%"
          }, {
            timePeriod: "03:15",
            value: "6.28%",
            hohRate: "--",
            dodRate: "-0.42%",
            wowRate: "0.77%"
          }, {
            timePeriod: "03:20",
            value: "7.08%",
            hohRate: "--",
            dodRate: "0.19%",
            wowRate: "0.6%"
          }, {
            timePeriod: "03:25",
            value: "6.27%",
            hohRate: "--",
            dodRate: "-0.75%",
            wowRate: "0.96%"
          }, {
            timePeriod: "03:30",
            value: "7.95%",
            hohRate: "--",
            dodRate: "2.59%",
            wowRate: "0.65%"
          }, {
            timePeriod: "03:35",
            value: "7.62%",
            hohRate: "--",
            dodRate: "-0.22%",
            wowRate: "2.46%"
          }, {
            timePeriod: "03:40",
            value: "7.62%",
            hohRate: "--",
            dodRate: "1.07%",
            wowRate: "3.48%"
          }, {
            timePeriod: "03:45",
            value: "6.80%",
            hohRate: "--",
            dodRate: "-0.3%",
            wowRate: "-0.26%"
          }, {
            timePeriod: "03:50",
            value: "7.22%",
            hohRate: "--",
            dodRate: "0.66%",
            wowRate: "-0.81%"
          }, {
            timePeriod: "03:55",
            value: "5.39%",
            hohRate: "--",
            dodRate: "-2.41%",
            wowRate: "-0.6%"
          }, {
            timePeriod: "04:00",
            value: "6.18%",
            hohRate: "--",
            dodRate: "-0.12%",
            wowRate: "2.01%"
          }, {
            timePeriod: "04:05",
            value: "7.42%",
            hohRate: "--",
            dodRate: "1.2%",
            wowRate: "0.94%"
          }, {
            timePeriod: "04:10",
            value: "9.13%",
            hohRate: "--",
            dodRate: "1.62%",
            wowRate: "3.53%"
          }, {
            timePeriod: "04:15",
            value: "5.58%",
            hohRate: "--",
            dodRate: "-0.91%",
            wowRate: "0.26%"
          }, {
            timePeriod: "04:20",
            value: "6.19%",
            hohRate: "--",
            dodRate: "0.74%",
            wowRate: "-1.44%"
          }, {
            timePeriod: "04:25",
            value: "5.14%",
            hohRate: "--",
            dodRate: "-5.92%",
            wowRate: "-1.08%"
          }, {
            timePeriod: "04:30",
            value: "6.49%",
            hohRate: "--",
            dodRate: "-1.59%",
            wowRate: "1.07%"
          }, {
            timePeriod: "04:35",
            value: "5.79%",
            hohRate: "--",
            dodRate: "-1.86%",
            wowRate: "1.46%"
          }, {
            timePeriod: "04:40",
            value: "3.87%",
            hohRate: "--",
            dodRate: "-5.56%",
            wowRate: "-2.9%"
          }, {
            timePeriod: "04:45",
            value: "7.69%",
            hohRate: "--",
            dodRate: "1.95%",
            wowRate: "0.4%"
          }, {
            timePeriod: "04:50",
            value: "9.09%",
            hohRate: "--",
            dodRate: "5.5%",
            wowRate: "-0.1%"
          }, {
            timePeriod: "04:55",
            value: "8.70%",
            hohRate: "--",
            dodRate: "3.08%",
            wowRate: "1.09%"
          }, {
            timePeriod: "05:00",
            value: "6.51%",
            hohRate: "--",
            dodRate: "-0.9%",
            wowRate: "1.86%"
          }, {
            timePeriod: "05:05",
            value: "7.04%",
            hohRate: "--",
            dodRate: "0.3%",
            wowRate: "0.83%"
          }, {
            timePeriod: "05:10",
            value: "9.82%",
            hohRate: "--",
            dodRate: "-2.78%",
            wowRate: "2.94%"
          }, {
            timePeriod: "05:15",
            value: "7.19%",
            hohRate: "--",
            dodRate: "4.9%",
            wowRate: "2.61%"
          }, {
            timePeriod: "05:20",
            value: "4.26%",
            hohRate: "--",
            dodRate: "-3.29%",
            wowRate: "-1.96%"
          }, {
            timePeriod: "05:25",
            value: "2.82%",
            hohRate: "--",
            dodRate: "-0.78%",
            wowRate: "-3.73%"
          }, {
            timePeriod: "05:30",
            value: "6.00%",
            hohRate: "--",
            dodRate: "-3.85%",
            wowRate: "0.78%"
          }, {
            timePeriod: "05:35",
            value: "5.88%",
            hohRate: "--",
            dodRate: "1.78%",
            wowRate: "-2.63%"
          }, {
            timePeriod: "05:40",
            value: "3.68%",
            hohRate: "--",
            dodRate: "-1.4%",
            wowRate: "-2.99%"
          }, {
            timePeriod: "05:45",
            value: "9.15%",
            hohRate: "--",
            dodRate: "0.63%",
            wowRate: "3.97%"
          }, {
            timePeriod: "05:50",
            value: "5.15%",
            hohRate: "--",
            dodRate: "-5.86%",
            wowRate: "-0.3%"
          }, {
            timePeriod: "05:55",
            value: "5.59%",
            hohRate: "--",
            dodRate: "-7.19%",
            wowRate: "-2.55%"
          }, {
            timePeriod: "06:00",
            value: "7.92%",
            hohRate: "--",
            dodRate: "4.32%",
            wowRate: "1.42%"
          }, {
            timePeriod: "06:05",
            value: "5.15%",
            hohRate: "--",
            dodRate: "-2.73%",
            wowRate: "1.05%"
          }, {
            timePeriod: "06:10",
            value: "6.67%",
            hohRate: "--",
            dodRate: "0.12%",
            wowRate: "1.26%"
          }, {
            timePeriod: "06:15",
            value: "8.45%",
            hohRate: "--",
            dodRate: "3.79%",
            wowRate: "0.82%"
          }, {
            timePeriod: "06:20",
            value: "4.58%",
            hohRate: "--",
            dodRate: "-3.24%",
            wowRate: "-2.81%"
          }, {
            timePeriod: "06:25",
            value: "4.69%",
            hohRate: "--",
            dodRate: "-1.02%",
            wowRate: "-2.35%"
          }, {
            timePeriod: "06:30",
            value: "5.09%",
            hohRate: "--",
            dodRate: "0.17%",
            wowRate: "-0.79%"
          }, {
            timePeriod: "06:35",
            value: "5.37%",
            hohRate: "--",
            dodRate: "-0.52%",
            wowRate: "-2.03%"
          }, {
            timePeriod: "06:40",
            value: "7.62%",
            hohRate: "--",
            dodRate: "0.96%",
            wowRate: "1.5%"
          }, {
            timePeriod: "06:45",
            value: "3.23%",
            hohRate: "--",
            dodRate: "-1.16%",
            wowRate: "-2.25%"
          }, {
            timePeriod: "06:50",
            value: "7.09%",
            hohRate: "--",
            dodRate: "2.89%",
            wowRate: "0.78%"
          }, {
            timePeriod: "06:55",
            value: "3.33%",
            hohRate: "--",
            dodRate: "-2.06%",
            wowRate: "-2.65%"
          }, {
            timePeriod: "07:00",
            value: "5.20%",
            hohRate: "--",
            dodRate: "-0.78%",
            wowRate: "0.24%"
          }, {
            timePeriod: "07:05",
            value: "4.38%",
            hohRate: "--",
            dodRate: "-3.03%",
            wowRate: "-0.17%"
          }, {
            timePeriod: "07:10",
            value: "6.02%",
            hohRate: "--",
            dodRate: "-1.0%",
            wowRate: "2.76%"
          }, {
            timePeriod: "07:15",
            value: "7.00%",
            hohRate: "--",
            dodRate: "0.35%",
            wowRate: "3.97%"
          }, {
            timePeriod: "07:20",
            value: "3.48%",
            hohRate: "--",
            dodRate: "-1.35%",
            wowRate: "-0.14%"
          }, {
            timePeriod: "07:25",
            value: "4.28%",
            hohRate: "--",
            dodRate: "-0.62%",
            wowRate: "-2.79%"
          }, {
            timePeriod: "07:30",
            value: "3.30%",
            hohRate: "--",
            dodRate: "-3.55%",
            wowRate: "-2.28%"
          }, {
            timePeriod: "07:35",
            value: "5.64%",
            hohRate: "--",
            dodRate: "-0.01%",
            wowRate: "1.16%"
          }, {
            timePeriod: "07:40",
            value: "3.40%",
            hohRate: "--",
            dodRate: "-1.17%",
            wowRate: "-1.9%"
          }, {
            timePeriod: "07:45",
            value: "5.08%",
            hohRate: "--",
            dodRate: "1.01%",
            wowRate: "1.19%"
          }, {
            timePeriod: "07:50",
            value: "3.98%",
            hohRate: "--",
            dodRate: "-1.09%",
            wowRate: "-1.19%"
          }, {
            timePeriod: "07:55",
            value: "4.75%",
            hohRate: "--",
            dodRate: "-0.72%",
            wowRate: "0.4%"
          }, {
            timePeriod: "08:00",
            value: "4.57%",
            hohRate: "--",
            dodRate: "0.43%",
            wowRate: "0.17%"
          }, {
            timePeriod: "08:05",
            value: "4.64%",
            hohRate: "--",
            dodRate: "1.07%",
            wowRate: "-0.64%"
          }, {
            timePeriod: "08:10",
            value: "4.40%",
            hohRate: "--",
            dodRate: "-0.05%",
            wowRate: "-1.26%"
          }, {
            timePeriod: "08:15",
            value: "5.10%",
            hohRate: "--",
            dodRate: "0.03%",
            wowRate: "0.84%"
          }, {
            timePeriod: "08:20",
            value: "4.89%",
            hohRate: "--",
            dodRate: "0.71%",
            wowRate: "0.0%"
          }, {
            timePeriod: "08:25",
            value: "5.64%",
            hohRate: "--",
            dodRate: "-0.03%",
            wowRate: "0.85%"
          }, {
            timePeriod: "08:30",
            value: "4.54%",
            hohRate: "--",
            dodRate: "-1.2%",
            wowRate: "-0.74%"
          }, {
            timePeriod: "08:35",
            value: "3.12%",
            hohRate: "--",
            dodRate: "-1.81%",
            wowRate: "-1.17%"
          }, {
            timePeriod: "08:40",
            value: "4.10%",
            hohRate: "--",
            dodRate: "-0.77%",
            wowRate: "-0.86%"
          }, {
            timePeriod: "08:45",
            value: "4.85%",
            hohRate: "--",
            dodRate: "0.44%",
            wowRate: "0.19%"
          }, {
            timePeriod: "08:50",
            value: "4.90%",
            hohRate: "--",
            dodRate: "-1.99%",
            wowRate: "-1.3%"
          }, {
            timePeriod: "08:55",
            value: "4.93%",
            hohRate: "--",
            dodRate: "0.0%",
            wowRate: "0.58%"
          }, {
            timePeriod: "09:00",
            value: "4.40%",
            hohRate: "--",
            dodRate: "0.32%",
            wowRate: "-0.71%"
          }, {
            timePeriod: "09:05",
            value: "4.13%",
            hohRate: "--",
            dodRate: "-0.97%",
            wowRate: "-0.81%"
          }, {
            timePeriod: "09:10",
            value: "5.27%",
            hohRate: "--",
            dodRate: "-1.04%",
            wowRate: "-0.82%"
          }, {
            timePeriod: "09:15",
            value: "4.07%",
            hohRate: "--",
            dodRate: "-2.09%",
            wowRate: "-0.66%"
          }, {
            timePeriod: "09:20",
            value: "5.05%",
            hohRate: "--",
            dodRate: "-0.55%",
            wowRate: "0.5%"
          }, {
            timePeriod: "09:25",
            value: "4.04%",
            hohRate: "--",
            dodRate: "-2.43%",
            wowRate: "-1.08%"
          }, {
            timePeriod: "09:30",
            value: "5.16%",
            hohRate: "--",
            dodRate: "-0.99%",
            wowRate: "0.8%"
          }, {
            timePeriod: "09:35",
            value: "4.46%",
            hohRate: "--",
            dodRate: "-1.05%",
            wowRate: "-0.79%"
          }, {
            timePeriod: "09:40",
            value: "4.03%",
            hohRate: "--",
            dodRate: "-0.97%",
            wowRate: "-1.37%"
          }, {
            timePeriod: "09:45",
            value: "4.70%",
            hohRate: "--",
            dodRate: "0.12%",
            wowRate: "0.22%"
          }, {
            timePeriod: "09:50",
            value: "4.78%",
            hohRate: "--",
            dodRate: "0.18%",
            wowRate: "0.11%"
          }, {
            timePeriod: "09:55",
            value: "5.93%",
            hohRate: "--",
            dodRate: "0.53%",
            wowRate: "0.44%"
          }, {
            timePeriod: "10:00",
            value: "5.26%",
            hohRate: "--",
            dodRate: "0.01%",
            wowRate: "0.37%"
          }, {
            timePeriod: "10:05",
            value: "4.73%",
            hohRate: "--",
            dodRate: "0.89%",
            wowRate: "-1.22%"
          }, {
            timePeriod: "10:10",
            value: "5.29%",
            hohRate: "--",
            dodRate: "-0.22%",
            wowRate: "0.39%"
          }, {
            timePeriod: "10:15",
            value: "4.25%",
            hohRate: "--",
            dodRate: "-0.81%",
            wowRate: "-0.52%"
          }, {
            timePeriod: "10:20",
            value: "5.29%",
            hohRate: "--",
            dodRate: "-1.01%",
            wowRate: "0.6%"
          }, {
            timePeriod: "10:25",
            value: "4.95%",
            hohRate: "--",
            dodRate: "0.02%",
            wowRate: "-0.71%"
          }, {
            timePeriod: "10:30",
            value: "5.15%",
            hohRate: "--",
            dodRate: "0.81%",
            wowRate: "-0.28%"
          }, {
            timePeriod: "10:35",
            value: "4.11%",
            hohRate: "--",
            dodRate: "-1.56%",
            wowRate: "-1.23%"
          }, {
            timePeriod: "10:40",
            value: "4.95%",
            hohRate: "--",
            dodRate: "0.17%",
            wowRate: "-0.94%"
          }, {
            timePeriod: "10:45",
            value: "4.85%",
            hohRate: "--",
            dodRate: "0.39%",
            wowRate: "0.17%"
          }, {
            timePeriod: "10:50",
            value: "5.12%",
            hohRate: "--",
            dodRate: "-0.11%",
            wowRate: "0.08%"
          }, {
            timePeriod: "10:55",
            value: "5.13%",
            hohRate: "--",
            dodRate: "-0.67%",
            wowRate: "-0.45%"
          }, {
            timePeriod: "11:00",
            value: "4.56%",
            hohRate: "--",
            dodRate: "-1.18%",
            wowRate: "0.27%"
          }, {
            timePeriod: "11:05",
            value: "5.00%",
            hohRate: "--",
            dodRate: "0.26%",
            wowRate: "0.08%"
          }, {
            timePeriod: "11:10",
            value: "4.98%",
            hohRate: "--",
            dodRate: "-0.12%",
            wowRate: "1.14%"
          }, {
            timePeriod: "11:15",
            value: "5.18%",
            hohRate: "--",
            dodRate: "0.59%",
            wowRate: "-0.68%"
          }, {
            timePeriod: "11:20",
            value: "4.67%",
            hohRate: "--",
            dodRate: "-0.88%",
            wowRate: "-0.16%"
          }, {
            timePeriod: "11:25",
            value: "5.23%",
            hohRate: "--",
            dodRate: "-0.35%",
            wowRate: "0.77%"
          }, {
            timePeriod: "11:30",
            value: "5.22%",
            hohRate: "--",
            dodRate: "0.51%",
            wowRate: "-0.05%"
          }, {
            timePeriod: "11:35",
            value: "4.70%",
            hohRate: "--",
            dodRate: "0.64%",
            wowRate: "-0.27%"
          }, {
            timePeriod: "11:40",
            value: "4.34%",
            hohRate: "--",
            dodRate: "-0.65%",
            wowRate: "0.58%"
          }, {
            timePeriod: "11:45",
            value: "4.66%",
            hohRate: "--",
            dodRate: "-0.54%",
            wowRate: "-0.86%"
          }, {
            timePeriod: "11:50",
            value: "4.62%",
            hohRate: "--",
            dodRate: "-0.4%",
            wowRate: "-0.89%"
          }, {
            timePeriod: "11:55",
            value: "5.06%",
            hohRate: "--",
            dodRate: "0.87%",
            wowRate: "1.0%"
          }, {
            timePeriod: "12:00",
            value: "4.86%",
            hohRate: "--",
            dodRate: "0.64%",
            wowRate: "-0.02%"
          }, {
            timePeriod: "12:05",
            value: "4.93%",
            hohRate: "--",
            dodRate: "0.58%",
            wowRate: "0.64%"
          }, {
            timePeriod: "12:10",
            value: "4.91%",
            hohRate: "--",
            dodRate: "0.19%",
            wowRate: "-0.7%"
          }, {
            timePeriod: "12:15",
            value: "4.72%",
            hohRate: "--",
            dodRate: "-0.8%",
            wowRate: "0.47%"
          }, {
            timePeriod: "12:20",
            value: "5.80%",
            hohRate: "--",
            dodRate: "0.74%",
            wowRate: "1.12%"
          }, {
            timePeriod: "12:25",
            value: "4.85%",
            hohRate: "--",
            dodRate: "-0.88%",
            wowRate: "-0.79%"
          }, {
            timePeriod: "12:30",
            value: "4.95%",
            hohRate: "--",
            dodRate: "0.78%",
            wowRate: "0.05%"
          }, {
            timePeriod: "12:35",
            value: "4.98%",
            hohRate: "--",
            dodRate: "0.76%",
            wowRate: "-0.74%"
          }, {
            timePeriod: "12:40",
            value: "4.93%",
            hohRate: "--",
            dodRate: "0.73%",
            wowRate: "-0.2%"
          }, {
            timePeriod: "12:45",
            value: "4.37%",
            hohRate: "--",
            dodRate: "-1.36%",
            wowRate: "-0.48%"
          }, {
            timePeriod: "12:50",
            value: "4.42%",
            hohRate: "--",
            dodRate: "-0.44%",
            wowRate: "0.09%"
          }, {
            timePeriod: "12:55",
            value: "4.73%",
            hohRate: "--",
            dodRate: "-0.54%",
            wowRate: "-0.61%"
          }, {
            timePeriod: "13:00",
            value: "5.83%",
            hohRate: "--",
            dodRate: "1.7%",
            wowRate: "1.53%"
          }, {
            timePeriod: "13:05",
            value: "4.74%",
            hohRate: "--",
            dodRate: "-0.69%",
            wowRate: "0.17%"
          }, {
            timePeriod: "13:10",
            value: "4.62%",
            hohRate: "--",
            dodRate: "-1.08%",
            wowRate: "-1.12%"
          }, {
            timePeriod: "13:15",
            value: "5.19%",
            hohRate: "--",
            dodRate: "1.01%",
            wowRate: "1.12%"
          }, {
            timePeriod: "13:20",
            value: "4.79%",
            hohRate: "--",
            dodRate: "-0.26%",
            wowRate: "0.11%"
          }, {
            timePeriod: "13:25",
            value: "4.47%",
            hohRate: "--",
            dodRate: "-0.33%",
            wowRate: "-0.93%"
          }, {
            timePeriod: "13:30",
            value: "5.05%",
            hohRate: "--",
            dodRate: "-0.28%",
            wowRate: "-0.07%"
          }, {
            timePeriod: "13:35",
            value: "4.96%",
            hohRate: "--",
            dodRate: "-0.04%",
            wowRate: "-0.64%"
          }, {
            timePeriod: "13:40",
            value: "5.39%",
            hohRate: "--",
            dodRate: "-0.13%",
            wowRate: "0.33%"
          }, {
            timePeriod: "13:45",
            value: "5.32%",
            hohRate: "--",
            dodRate: "0.84%",
            wowRate: "0.59%"
          }, {
            timePeriod: "13:50",
            value: "5.09%",
            hohRate: "--",
            dodRate: "-0.19%",
            wowRate: "0.3%"
          }, {
            timePeriod: "13:55",
            value: "5.55%",
            hohRate: "--",
            dodRate: "0.98%",
            wowRate: "0.85%"
          }, {
            timePeriod: "14:00",
            value: "5.39%",
            hohRate: "--",
            dodRate: "0.88%",
            wowRate: "0.31%"
          }, {
            timePeriod: "14:05",
            value: "5.44%",
            hohRate: "--",
            dodRate: "0.38%",
            wowRate: "0.28%"
          }, {
            timePeriod: "14:10",
            value: "5.38%",
            hohRate: "--",
            dodRate: "-0.0%",
            wowRate: "-0.08%"
          }, {
            timePeriod: "14:15",
            value: "4.92%",
            hohRate: "--",
            dodRate: "-0.14%",
            wowRate: "-0.19%"
          }, {
            timePeriod: "14:20",
            value: "4.69%",
            hohRate: "--",
            dodRate: "0.06%",
            wowRate: "0.37%"
          }, {
            timePeriod: "14:25",
            value: "4.77%",
            hohRate: "--",
            dodRate: "0.58%",
            wowRate: "-0.84%"
          }, {
            timePeriod: "14:30",
            value: "5.63%",
            hohRate: "--",
            dodRate: "1.42%",
            wowRate: "-0.28%"
          }, {
            timePeriod: "14:35",
            value: "5.89%",
            hohRate: "--",
            dodRate: "0.56%",
            wowRate: "0.53%"
          }, {
            timePeriod: "14:40",
            value: "4.57%",
            hohRate: "--",
            dodRate: "-0.44%",
            wowRate: "-0.72%"
          }, {
            timePeriod: "14:45",
            value: "5.03%",
            hohRate: "--",
            dodRate: "0.17%",
            wowRate: "0.1%"
          }, {
            timePeriod: "14:50",
            value: "5.20%",
            hohRate: "--",
            dodRate: "-0.11%",
            wowRate: "-0.07%"
          }, {
            timePeriod: "14:55",
            value: "4.48%",
            hohRate: "--",
            dodRate: "-0.74%",
            wowRate: "-1.09%"
          }, {
            timePeriod: "15:00",
            value: "5.12%",
            hohRate: "--",
            dodRate: "0.67%",
            wowRate: "-0.42%"
          }, {
            timePeriod: "15:05",
            value: "4.32%",
            hohRate: "--",
            dodRate: "-1.11%",
            wowRate: "-0.43%"
          }, {
            timePeriod: "15:10",
            value: "4.23%",
            hohRate: "--",
            dodRate: "-0.45%",
            wowRate: "-1.56%"
          }, {
            timePeriod: "15:15",
            value: "4.86%",
            hohRate: "--",
            dodRate: "1.07%",
            wowRate: "1.11%"
          }, {
            timePeriod: "15:20",
            value: "5.38%",
            hohRate: "--",
            dodRate: "0.24%",
            wowRate: "0.47%"
          }, {
            timePeriod: "15:25",
            value: "4.82%",
            hohRate: "--",
            dodRate: "1.24%",
            wowRate: "-0.65%"
          }, {
            timePeriod: "15:30",
            value: "5.25%",
            hohRate: "--",
            dodRate: "0.23%",
            wowRate: "0.0%"
          }, {
            timePeriod: "15:35",
            value: "5.13%",
            hohRate: "--",
            dodRate: "0.01%",
            wowRate: "-0.74%"
          }, {
            timePeriod: "15:40",
            value: "5.12%",
            hohRate: "--",
            dodRate: "1.05%",
            wowRate: "0.49%"
          }, {
            timePeriod: "15:45",
            value: "4.98%",
            hohRate: "--",
            dodRate: "-0.28%",
            wowRate: "-0.04%"
          }]
        },
        {
          label: "文本卡",
          size: "690*380",
          type: "node",
          x: 0,
          y: 0,
          shape: "trendNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]],
          isDoingStart: true,
          id: 58,
          name: "国内酒店抵扣有效订-趋势图",
          enName: "hotel_mile_sorders_rate",
          groupType: 3,
          period: '1h',
          card: {value: "109.00", dodRate: "-209.68%", wowRate: "430.42%", hohRate: "230.03%", time: "14:30 - 14:35"},
          viewComparison: ["dod", "wow"],
          table: {},
          trend: {
            legendData: ["昨日", "上时段", "今日"],
            aliasData: ["01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00"],
            todayData: ["617.00", "343.00", "180.00", "126.00", "71.00", "84.00", "182.00", "343.00", "657.00", "920.00", "1089.00", "1257.00", "1141.00"],
            periodData: ["0.00", "617.00", "343.00", "180.00", "126.00", "71.00", "84.00", "182.00", "343.00", "657.00", "920.00", "1089.00", "1257.00"],
            yesterdayData: ["523.00", "314.00", "164.00", "93.00", "74.00", "92.00", "197.00", "371.00", "674.00", "992.00", "1140.00", "1355.00", "1181.00"],
            weekData: null
          }
        },
        {
          label: "混合图",
          size: "690*380",
          type: "node",
          x: 0,
          y: 0,
          shape: "trendBarNode",
          color: "#1890ff",
          image: "https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg",
          inPoints: [[0, 0.5]],
          outPoints: [[1, 0.5]],
          isDoingStart: true,
          id: 51,
          name: "国内酒店抵扣-混合图",
          enName: "hotel_mile_sorders_rate",
          groupType: 3,
          period: '1h',
          card: {value: "109.00", dodRate: "-209.68%", wowRate: "430.42%", hohRate: "230.03%", time: "14:30 - 14:35"},
          viewComparison: ["dod", "wow"],
          table: {},
          trend: {
            legendData: ["昨日环比", "上周同期环比", "数值"],
            aliasData: ["2024-01-18", "2024-01-19", "2024-01-20", "2024-01-21", "2024-01-22", "2024-01-23", "2024-01-24", "2024-01-25", "2024-01-26", "2024-01-27", "2024-01-28", "2024-01-29", "2024-01-30"],
            todayData: ["6353.00", "7319.00", "6875.00", "7423.00", "6713.00", "6755.00", "7550.00", "7189.00", "6622.00", "4922.00", "4987.00", "4257.00", "3535.00"],
            periodData: null,
            yesterdayData: ["6.79", "15.21", "-6.07", "7.97", "-9.56", "0.63", "11.77", "-4.78", "-7.89", "-25.67", "1.32", "-14.64", "-16.96"],
            weekData: ["112.40", "86.14", "53.22", "38.05", "26.92", "22.04", "26.91", "13.16", "-9.52", "-28.41", "-32.82", "-36.59", "-47.67"]
          }
        },
      ]
    };
  },
  created() {
    this.bindEvent();
  },
  methods: {
    handleDragstart(e) {
      this.offsetX = e.offsetX;
      this.offsetY = e.offsetY;
    },
    handleDragEnd(e, item) {
      let data = {};
      Object.assign(data, item);
      data.offsetX = this.offsetX;
      data.offsetY = this.offsetY;
      if (this.page) {
        const graph = this.page.graph;
        const xy = graph.getPointByClient(e.x, e.y);
        data.x = xy.x;
        data.y = xy.y;
        if (item.size) {
          data.size = item.size.split("*");
        }
        data.type = "node";
        this.command.executeCommand("add", [data]);
      }
    },
    bindEvent() {
      eventBus.$on("afterAddPage", page => {
        this.page = page;
        this.command = page.command;
      });
    }
  }
};
</script>

<style scoped>
.itempannel {
  height: 100%;
  position: absolute;
  left: 0;
  z-index: 2;
  background: #f7f9fb;
  width: 240px !important;
  padding-top: 8px;
  border-right: 1px solid #e6e9ed;
}

.itempannel ul {
  padding: 0px;
  padding-left: 4px !important;
}

.itempannel li {
  display: flex;
  align-items: center; /* 使用 flex 布局实现垂直居中对齐 */
  color: rgba(0, 0, 0, 0.65);
  border-radius: 4px;
  width: 227px;
  height: 30px; /* 增加 li 元素的高度 */
  padding-left: 4px;
  border: 1px solid rgba(0, 0, 0, 0);
  list-style-type: none;
}

.itempannel li:hover {
  background: white;
  border: 1px solid #ced4d9;
  cursor: move;
}

.itempannel .pannel-type-icon {
  width: 16px;
  height: 16px;
  display: inline-block;
  vertical-align: middle;
  margin-right: 8px;
}

.item-name {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  display: inline-block;
  max-width: 210px; /* 修改为更合适的值 */
  vertical-align: middle; /* 垂直居中对齐 */
}
</style>